name = "rechenkiste"
main = "./dist/_worker.js/index.js"
compatibility_date = "2025-11-28"
compatibility_flags = ["nodejs_compat"]

# Custom domain - aktivieren wenn DNS konfiguriert ist
# routes = [{ pattern = "rechenkiste.casoon.dev", custom_domain = true }]

[assets]
directory = "./dist"
binding = "ASSETS"

# KV f√ºr Astro Sessions
[[kv_namespaces]]
binding = "SESSION"
id = "21fa37fe76934de8afe152b0d032a845"
